### ISSUE TITLE
сайт не подымается в дев режиме

### ISSUE THREAD

**Issue by coreer** [iliakan/javascript-nodejs#216]
/pr/javascript-nodejs/node_modules/koa-passport/lib/index.js:3
passport.framework(require('./framework/koa')())
         ^
TypeError: undefined is not a function
    at Object.<anonymous> (/pr/javascript-nodejs/node_modules/koa-passport/lib/index.js:3:10)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/pr/javascript-nodejs/handlers/passport.js:2:18)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Application.requireHandler (/pr/javascript-nodejs/modules/application.js:92:22)
    at Object.<anonymous> (/pr/javascript-nodejs/modules/app.js:76:5)

**Comment by iliakan** [comment]
Баг в NPM.

**Comment by coreer** [comment]
Переустановил полностью node на 0.11.16
Прошелся по интрукции устновки снова, при npm install были следующие проблемы:

npm WARN engine directory@0.0.61: wanted: {"node":"~0.6.1"} (current: {"node":"0.11.16","npm":"2.3.0"})
 
> v8flags@1.0.8 install /Users/aieremenko/Documents/pr/javascript-nodejs/node_modules/gulp/node_modules/v8flags
> node fetch.js

flags for v8 3.28.73 cached.
 
> fsevents@0.3.5 install /Users/aieremenko/Documents/pr/javascript-nodejs/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished
npm WARN excluding symbolic link test/symlinks/dir1/dangling-symlink -> does-not-exist
 
> fsevents@0.2.1 install /Users/aieremenko/Documents/pr/javascript-nodejs/node_modules/gulp-dir-sync/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:339:13: error: no member named 'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


...........................И ТАК ДАЛЕЕ...................


fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/aieremenko/Documents/pr/javascript-nodejs/node_modules/gulp-dir-sync/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.11.16
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.2.1
 
> optipng-bin@2.0.4 postinstall /Users/aieremenko/Documents/pr/javascript-nodejs/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

/Users/aieremenko/Documents/pr/javascript-nodejs/node_modules/request/node_modules/hawk/node_modules/hoek/lib/index.js:236
});
 ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/aieremenko/Documents/pr/javascript-nodejs/node_modules/request/node_modules/hawk/node_modules/hoek/index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
 


При запуске опять таки проблема в с паспортом:

/Users/aieremenko/Documents/pr/javascript-nodejs/node_modules/koa-passport/lib/index.js:3
passport.framework(require('./framework/koa')())
         ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/aieremenko/Documents/pr/javascript-nodejs/node_modules/koa-passport/lib/index.js:3:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)


Устанавливал через инталятор для мака, возможно нужно собирать в ручную со специфичными флагами?

**Comment by iliakan** [comment]
Это бага в NPM по виду, я её отрепортил. 
У меня тоже Mac, работает, вручную доставлял passport после чистки всех кешей.

**Comment by iliakan** [comment]
зайди внутрь koa-passport и npm i passport

**Comment by coreer** [comment]
Все получилось!
Спасибо!
