### ISSUE TITLE
Сайт не работает без подключения туториала

### ISSUE THREAD

**Issue by coreer** [iliakan/javascript-nodejs#217]
12:17:38.261Z ERROR app: <-- GET /tutorial (reqId=6c0b1b62-55ed-4eb7-8e2e-e831df630474, event=request-end, method=GET, status=500, timeDuration=386, length=null)
12:17:38.261Z ERROR app: TypeError: Cannot read property 'id' of undefined (reqId=6c0b1b62-55ed-4eb7-8e2e-e831df630474)
12:17:38.264Z ERROR app: (reqId=6c0b1b62-55ed-4eb7-8e2e-e831df630474)
    TypeError: Cannot read property 'id' of undefined
        at populateContent (/Users/aieremenko/Documents/pr/javascript-nodejs/handlers/tutorial/controller/tutorial.js:83:50)
        at GeneratorFunctionPrototype.next (native)
        at renderTutorial (/Users/aieremenko/Documents/pr/javascript-nodejs/handlers/tutorial/controller/tutorial.js:45:12)
        at GeneratorFunctionPrototype.next (native)
        at Object.get (/Users/aieremenko/Documents/pr/javascript-nodejs/handlers/tutorial/controller/tutorial.js:16:23)
        at GeneratorFunctionPrototype.next (native)
        at Object.dispatch (/Users/aieremenko/Documents/pr/javascript-nodejs/node_modules/koa-router/lib/router.js:97:44)
        at GeneratorFunctionPrototype.next (native)
        at Object.<anonymous> (/Users/aieremenko/Documents/pr/javascript-nodejs/modules/lib/lazyRouterMiddleware.js:14:23)
        at GeneratorFunctionPrototype.next (native)
        at Object.wrapMiddleware (/Users/aieremenko/Documents/pr/javascript-nodejs/modules/lib/mountHandlerMiddleware.js:32:33)
        at GeneratorFunctionPrototype.next (native)
        at Object.<anonymous> (/Users/aieremenko/Documents/pr/javascript-nodejs/modules/application.js:87:14)
        at GeneratorFunctionPrototype.next (native)
        at Object.<anonymous> (/Users/aieremenko/Documents/pr/javascript-nodejs/node_modules/koa-mount/index.js:52:33)
        at GeneratorFunctionPrototype.next (native)

В браузере видно тот же стектрейс:)

**Comment by iliakan** [comment]
Э, ну это потому что оно в туториал заходит по умолчанию.
Сам движок поднимается.

**Comment by coreer** [comment]
Доступ к туториалу получить нельзя пока, да?(smirk)

**Comment by iliakan** [comment]
Доступ к туториалу не обязателен, обновил фикстуры, вот:

```
git pull origin master
./gulp db:load --from fixture/init --harmony
./gulp db:load --from fixture/tutorial --harmony
./dev
```

У меня так заработало.

**Comment by coreer** [comment]
Заработало. Спасибо!(y)
