### ISSUE TITLE
No gulpfile found

### ISSUE THREAD

**Issue by ArtNekki** [iliakan/javascript-nodejs#689]
Здравствуйте, Илья! Такая проблема. Устанавливаю пакеты все ок:
npm install -g mocha bunyan gulp nodemon.

Далее делаю:
gulp config:nginx --prefix /opt/local/etc/nginx --root /opt/local/www/own/javascript-nodejs --env development.

Возникает ошибка:  No gulp file found.  

Хотя gulp установлен. В чем может быть проблема?

**Comment by iliakan** [comment]
А вы в директорию проекта зашли перед этим?

**Comment by ArtNekki** [comment]
Из директории   /opt/local/www/own/javascript-nodejs запускаю:
gulp config:nginx --prefix /opt/local/etc/nginx --root /opt/local/www/own/javascript-nodejs --env development,

такая ошибка:

currentLng set to: ru
[22:51:07] Using gulpfile /opt/local/www/own/javascript-nodejs/gulpfile.js
[22:51:07] Starting 'config:nginx'...
loaded file: locales/ru/translation.json
loaded file: locales/en/translation.json
connect ECONNREFUSED 127.0.0.1:27017 Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:812:11)
    at exports._exceptionWithHostPort (util.js:835:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1048:14) undefined
-------------------------------------------------------------------------------------------------------------------------------------------
Из директории   /opt/local/www/own/javascript-nodejs запускаю:
gulp db:load --from fixture/init , 

такая ошибка:

currentLng set to: ru
[22:47:10] Using gulpfile /opt/local/www/own/javascript-nodejs/gulpfile.js
[22:47:10] Starting 'db:load'...
[22:47:11] loading db /opt/local/www/own/javascript-nodejs/fixture/init
loaded file: locales/ru/translation.json
loaded file: locales/en/translation.json
connect ECONNREFUSED 127.0.0.1:27017 Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:812:11)
    at exports._exceptionWithHostPort (util.js:835:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1048:14) undefined

-----------------------------------------------------
Не пойму чего не хватает..

**Comment by iliakan** [comment]
К Mongo не может присоединиться.

**Comment by ArtNekki** [comment]
Спасибо! Разобрался с mongo, по инструкции все установилось. При запуске nginx пишет : 

nginx: [emerg] unknown directive "geoip_country" in /opt/local/etc/nginx/http/geoip.conf:2

и для запуска сайта нужно где-то ввести: "./dev" ?  если да, то где?
