### ISSUE TITLE
SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by Splintex** [iliakan/javascript-nodejs#766]
На стадии  [конфигурации Nginx](https://github.com/iliakan/javascript-nodejs/blob/master/Install.md#6-Конфигурация-nginx) вылетает ошибка:
```
Eugenes-MacBook-Pro:javascript-nodejs Eugene$ gulp config:nginx --prefix /opt/local/etc/nginx --root /js/javascript-nodejs --env development --clear 
/Users/Eugene/js/javascript-nodejs/modules/cls.js:14
  app.use(function*(next) {
                  ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Eugene/js/javascript-nodejs/gulpfile.js:18:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```
Не могу понять в чем дело.

**Comment by iliakan** [comment]
`node -v` ?

**Comment by Splintex** [comment]
v0.12.7
