### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:27017

### ISSUE THREAD

**Issue by stevermeister** [iliakan/javascript-nodejs#892]
при запуске команды 
    

> Если Nginx у вас уже стоит

> $ npm --silent run gulp -- config:nginx --prefix /opt/local/etc/nginx --root /js/javascript-nodejs --env development

```
[11:46:07] Using gulpfile ~/workspace/javascript-nodejs/gulpfile.js
[11:46:07] Starting 'config:nginx'...
connect ECONNREFUSED 127.0.0.1:27017 Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:893:11)
    at exports._exceptionWithHostPort (util.js:916:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1075:14) undefined
```

**Comment by iliakan** [comment]
Install & run mongodb.
